#eureka:
#  instance:
#    hostname: 10.226.50.201
#  client:
#    fetch-registry: false
#    register-with-eureka: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761

#  address:  10.226.50.201









